### ISSUE TITLE
Item price not updated in cart

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/magento2-module-retailer-offer#1]
The items already in cart don't take the new offer price when changing the retailer or the pickup date.

**Comment by romainruaud** [comment]
Hello @AymericJoubert, I will need more informations about this issue since I am not able to reproduce it. Can you be more precise ? Thanks.

**Comment by romainruaud** [comment]
Fixed on the retailer module. See https://github.com/Smile-SA/magento2-module-retailer/commit/9cd673cd4489b3a4b1e2520302434a4b68e032ff
