### ISSUE TITLE
Errors during compilation: Smile\RetailerOffer\Model\Layer\Filter\Price

### ISSUE THREAD

**Issue by samc2810** [Smile-SA/magento2-module-retailer-offer#30]
https://github.com/Smile-SA/magento2-module-retailer-offer/blob/084157018f38610c43afe7b83741ec747490188b/Model/Layer/Filter/Price.php#L100

Hi there we are getting following error sind yesterday
Errors during compilation:
        Smile\RetailerOffer\Model\Layer\Filter\Price
                Incompatible argument type: Required type: array. Actual type: \Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory; File: 
/var/www/html/vendor/smile/module-retailer-offer/Model/Layer/Filter/Price.php

apparantly you are passing $queryFactory to the parent::__construct and the parent class does not allow this
the weird thing is that we are using this extension since two months and the error appeared yesterday only. Any ideas how we could fix this?

Cheers Sam

**Comment by Fdec** [comment]
Hi samc281

What is your magento version ?

**Comment by samc2810** [comment]
We are using 2.2.3
but as I said, it was working since october

**Comment by samc2810** [comment]
I even updated to 2.2.6 but still the same problem
and upgraded both elasticsuite and retailer from smile

the constructors in both the classes is same
\Smile\ElasticsuiteCatalog\Model\Layer\Filter\Price
\Smile\RetailerOffer\Model\Layer\Filter\Price

![image](https://user-images.githubusercontent.com/1092318/49247564-e3ea2c00-f417-11e8-9cc8-3fe14bfc4ebc.png)

**Comment by samc2810** [comment]
Hi @Fdec 
any updates?

**Comment by Fdec** [comment]
Hi samc2810

In your file Smile\ElasticsuiteCatalog\Model\Layer\Filter\Price, have you got this constructor ?
param $queryFactory is require now 

`public function __construct(
        \Magento\Catalog\Model\Layer\Filter\ItemFactory $filterItemFactory,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Catalog\Model\Layer $layer,
        \Magento\Catalog\Model\Layer\Filter\Item\DataBuilder $itemDataBuilder,
        \Magento\Catalog\Model\ResourceModel\Layer\Filter\Price $resource,
        \Magento\Customer\Model\Session $customerSession,
        \Magento\Framework\Search\Dynamic\Algorithm $priceAlgorithm,
        \Magento\Framework\Pricing\PriceCurrencyInterface $priceCurrency,
        \Magento\Catalog\Model\Layer\Filter\Dynamic\AlgorithmFactory $algorithmFactory,
        \Magento\Catalog\Model\Layer\Filter\DataProvider\PriceFactory $dataProviderFactory,
        \Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory $queryFactory,
        array $data = []
    ) {
        parent::__construct(
            $filterItemFactory,
            $storeManager,
            $layer,
            $itemDataBuilder,
            $resource,
            $customerSession,
            $priceAlgorithm,
            $priceCurrency,
            $algorithmFactory,
            $dataProviderFactory,
            $data
        );

        $this->dataProvider    = $dataProviderFactory->create(['layer' => $this->getLayer()]);
        $this->customerSession = $customerSession;
        $this->priceCurrency   = $priceCurrency;
        $this->queryFactory    = $queryFactory;
    }`

**Comment by Fdec** [comment]
No response since 2018. 
I close it
