### ISSUE TITLE
Filter additional product listing blocks

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/magento2-module-retailer-offer#9]
Despite the filtering works properly on the layer when using Drive mode, other blocks are still showing products without filtering : 

- upsell / crossell / related
- any product listing block

We should apply the filtering on those blocks too.

**Comment by Fdec** [comment]
Hi @romainruaud 
Is it still relevant ?

**Comment by Fdec** [comment]
Hi @romainruaud 

Because no response I close this old issue.
